/**
 * IPC 通道常量
 * 统一管理 main 和 renderer 进程间通信的通道名
 */

export const IPC_CHANNELS = {
  KNOWLEDGE: {
    VAULT_LIST: 'knowledge:v3:vault:list',
    VAULT_GET: 'knowledge:v3:vault:get',
    VAULT_CREATE: 'knowledge:v3:vault:create',
    VAULT_RENAME: 'knowledge:v3:vault:rename',
    VAULT_DELETE: 'knowledge:v3:vault:delete',
    TREE_GET: 'knowledge:v3:tree:get',
    GROUP_CREATE: 'knowledge:v3:group:create',
    GROUP_RENAME: 'knowledge:v3:group:rename',
    GROUP_DELETE: 'knowledge:v3:group:delete',
    TREE_MOVE: 'knowledge:v3:tree:move',
    CONTENT_LIST: 'knowledge:v3:content:list',
    CONTENT_CREATE: 'knowledge:v3:content:create',
    CONTENT_RENAME: 'knowledge:v3:content:rename',
    CONTENT_DELETE: 'knowledge:v3:content:delete',
    DOCUMENT_GET: 'knowledge:v3:document:get',
    DOCUMENT_UPDATE: 'knowledge:v3:document:update',
    DOCUMENT_REPLACE: 'knowledge:v3:document:replace',
    DOCUMENT_NODES_INSERT: 'knowledge:v3:document:nodes:insert',
    DOCUMENT_NODES_APPEND: 'knowledge:v3:document:nodes:append',
    DOCUMENT_NODE_REPLACE: 'knowledge:v3:document:node:replace',
    DOCUMENT_NODE_PATCH: 'knowledge:v3:document:node:patch',
    DOCUMENT_TEXT_REPLACE: 'knowledge:v3:document:text:replace',
    DOCUMENT_NODES_DELETE: 'knowledge:v3:document:nodes:delete',
    DOCUMENT_RESOURCE_INSERT: 'knowledge:v3:document:resource:insert',
    CANVAS_GET: 'knowledge:v3:canvas:get',
    CANVAS_CREATE: 'knowledge:v3:canvas:create',
    CANVAS_REPLACE: 'knowledge:v3:canvas:replace',
    CANVAS_ELEMENTS_UPSERT: 'knowledge:v3:canvas:elements:upsert',
    CANVAS_ELEMENTS_PATCH: 'knowledge:v3:canvas:elements:patch',
    CANVAS_ELEMENTS_DELETE: 'knowledge:v3:canvas:elements:delete',
    CANVAS_ELEMENTS_REORDER: 'knowledge:v3:canvas:elements:reorder',
    CANVAS_FILES_UPSERT: 'knowledge:v3:canvas:files:upsert',
    CANVAS_FILES_DELETE: 'knowledge:v3:canvas:files:delete',
    CANVAS_DELETE: 'knowledge:v3:canvas:delete',
    MINDMAP_GET: 'knowledge:v3:mindmap:get',
    MINDMAP_CREATE: 'knowledge:v3:mindmap:create',
    MINDMAP_REPLACE: 'knowledge:v3:mindmap:replace',
    MINDMAP_NODE_INSERT: 'knowledge:v3:mindmap:node:insert',
    MINDMAP_NODE_PATCH: 'knowledge:v3:mindmap:node:patch',
    MINDMAP_NODE_MOVE: 'knowledge:v3:mindmap:node:move',
    MINDMAP_NODE_DELETE: 'knowledge:v3:mindmap:node:delete',
    MINDMAP_DELETE: 'knowledge:v3:mindmap:delete',
    ASSET_IMPORT: 'knowledge:v3:asset:import',
    ASSET_GET: 'knowledge:v3:asset:get',
    ASSET_DELETE: 'knowledge:v3:asset:delete',
    ASSET_OPEN: 'knowledge:v3:asset:open',
    ASSET_SAVE_AS: 'knowledge:v3:asset:save-as',
    SEARCH: 'knowledge:v3:search',
    CHANGED: 'knowledge:v3:changed',
  },
  FILE: {
    SELECT_IMAGE: 'file:selectImage',
    SELECT_ATTACHMENT: 'file:selectAttachment',
    DOWNLOAD_IMAGE: 'file:downloadImage',
    EXPORT_PDF: 'file:exportPDF',
    REVEAL_PDF_EXPORT: 'file:revealPDFExport',
    BEGIN_MARKDOWN_EXPORT: 'file:beginMarkdownExport',
    COMMIT_MARKDOWN_EXPORT: 'file:commitMarkdownExport',
    REVEAL_MARKDOWN_EXPORT: 'file:revealMarkdownExport',
    OPEN_LOCAL_FILE: 'file:openLocalFile',
  },
  SETTINGS: {
    GET_GENERAL: 'settings:getGeneral',
    SAVE_GENERAL: 'settings:saveGeneral',
    GET_AI: 'settings:getAI',
    SAVE_AI: 'settings:saveAI',
    GET_HOTKEYS: 'settings:getHotkeys',
    SAVE_HOTKEYS: 'settings:saveHotkeys',
    GET_MCP: 'settings:getMcp',
    SAVE_MCP: 'settings:saveMcp',
    GET_MCP_STATUS: 'settings:getMcpStatus',
    GET_MCP_URL: 'settings:getMcpUrl',
    RESET_MCP_TOKEN: 'settings:resetMcpToken',
    COPY_MCP_URL: 'settings:copyMcpUrl',
  },
  AI: {
    PROCESS: 'ai:process',
    CANCEL: 'ai:cancel',
  },
  WINDOW: {
    MINIMIZE: 'window:minimize',
    MAXIMIZE: 'window:maximize',
    CLOSE: 'window:close',
    CLOSE_REQUESTED: 'window:close-requested',
    CLOSE_READY: 'window:close-ready',
    IS_MAXIMIZED: 'window:isMaximized',
    MAXIMIZED_CHANGE: 'window:maximized',
  },
  APP: {
    GET_ASSET_PATH: 'app:getAssetPath',
  },
} as const

/**
 * 导出通道类型，便于类型推断
 */
export type IpcChannels = typeof IPC_CHANNELS
